Migrated from got to node-fetch package
BaseAdresseNationale/ban-plateforme pull request #195
Opened 2023-06-23 08:26 UTC by antoineludeau

2023-06-23 08:56 UTC, mmortier requested changes
Il faut utiliser un proxy avec node-fetch en le mettant dans le .env (tester si déclaré on l'uitlise sinon pas de proxy)

2023-06-27 12:06 UTC, IGNFBourcier requested changes

2023-06-27 12:11 UTC, mmortier commented on lib/util/api-depot.cjs
>        return
Je confirme ce que dit Florent il faut gérer le 404. Sinon le passage de proxy fonctionne.

2023-07-02 18:38 UTC, antoineludeau commented on lib/util/api-depot.cjs
>        return
Bien vu !

2023-07-03 15:18 UTC, mmortier approved these changes
Un log en plus, vérifié sur la commande "yarn compose 80410" qui n'a pas de BAL.

2023-07-04 12:24 UTC, antoineludeau commented
En effet, comme dit pas @mmortier, un log d'erreur a été ajouté quand le fetch répond en 4xx ou 5xx (ce qui n'était pas le cas avant). Au vu du comportement actuel du "compose" (et peut-être d'autre commandes/contextes pas encore vus), ce log d'erreur sera ajouté si la révision de la commune n'est pas trouvée coté api de dépôt (comportement actuel 'normal' pour déterminer si une BAL existe ou non).

2023-07-05 08:18 UTC, IGNFBourcier reviewed
faut -il que le proxy (conf en env) soit actif pour les script par default ? si c'est le cas il faudrait rajouter `require('dotenv').config()` ou la variable dans la commande
 pour les scripts 
	- Prepare-contours 
	- Build-geo 
	- Download-datasets

2023-07-05 08:18 UTC, IGNFBourcier commented on lib/api/legacy-routes.cjs
> +const fetch = require('../util/fetch.cjs')
impact ok: les retours (pbm token) de idefix passeront dans le catch

2023-07-05 08:18 UTC, IGNFBourcier commented on .env.sample
> +PORT=
```suggestion
PORT=5000
```
pas très important mais on l' perdu dans le transport

2023-07-05 09:23 UTC, antoineludeau commented
@IGNFBourcier : bien vu, j'ai ajouté `require('dotenv').config()` dans les scripts : 
- Prepare-contours
- Build-geo
- Download-datasets

2023-07-05 13:16 UTC, IGNFBourcier approved these changes

2023-07-05 13:34 UTC, merged