WIP : affichage des infos nomVoieAlt et LieuDitComplementNomAlt via API
BaseAdresseNationale/ban-plateforme pull request #24
Opened 2022-07-07 14:11 UTC by mmortier

On peut voir les infos quand elles existent via l'API : 
http://localhost:5000/lookup/02131_p1dza2_00001
"LieuDitComplementNomAlt": {
    "bre": "nomLDCBreton",
    "cos": "nomLDCCorse"
  },
http://localhost:5000/lookup/02131_p1dza2
"nomVoieAlt": {
    "bre": "nomVoieBreton",
    "cos": "nomVoieCorse"
  },

n'apparaissent pas dans le bon ordre.
+ tout le reste à faire, enregistrement dans BAN...

2022-07-20 09:50 UTC, mmortier commented
L'enregistrement des langues régionales dans la BAN est opérationnel pour les imports de BAL.
**_pour la collection voies :_**
        "_id" : ObjectId("62d7c33d53a91d31f61de27b"),
        "type" : "voie",
        "groupId" : "slug-00000-chemin-baltans",
        "idVoie" : "02131_y15it6",
        "idVoieFantoir" : null,
        "nomVoie" : "Chemin des Baltans",
"**nomVoieAlt**" : {
                "bre" : "nomVoieBreton",
                "cos" : "nomVoieCorse"
        },
        "sourceNomVoie" : "bal",
        "codeCommune" : "02131",
        "nomCommune" : "Bucy-le-Long",
        "codeAncienneCommune" : null,
        "nomAncienneCommune" : null,

**_Pour la collection numeros :_**  
  "_id" : ObjectId("62d7c166fca3ef12a95cb1e8"),
        "codeCommune" : "02131",
        "idVoie" : "02131_68ihck",
        "numero" : 1,
        "suffixe" : null,
        "lieuDitComplementNom" : null,
 "**lieuDitComplementNomAlt**" : {
                "bre" : "LDCNbre",
                "cos" : "LDCNCos"
        }, 
        "parcelles" : [ ],
        "sources" : [
                "bal"
        ],
        "certifie" : true,
        "position" : {
                "type" : "Point",
                "coordinates" : [
                        3.398872,
                        49.374724
                ]
        },
        "positionType" : null,
        "positions" : [
                {
                        "position" : {
                                "type" : "Point",
                                "coordinates" : [
                                        3.398872,
                                        49.374724
                                ]
                        },
                        "positionType" : null
                }
        ],
        "displayBBox" : [
                3.3982,
                49.3743,
                3.3996,
                49.3752
        ],
        "sourcePosition" : "bal",
        "lon" : 3.398872,
        "lat" : 49.374724,
        "x" : 728975.51,
        "y" : 6919540.54,
        "tiles" : [
                "12/2086/1400",
                "13/4173/2800",
                "14/8346/5600"
        ],
        "codeAncienneCommune" : null,
        "nomAncienneCommune" : null,
        "codePostal" : "02880",
        "libelleAcheminement" : "BUCY LE LONG",
        "adressesOriginales" : [
                {
                        "_id" : ObjectId("62d7c10359c499c16eb3fb47"),
                        "dataSource" : "bal",
                        "source" : "bal",
                        "idAdresse" : "02131_xxxx_00001",
                        "originalIdVoie" : "",
                        "numero" : 1,
                        "suffixe" : null,
                        "nomVoie" : "Chemin des Baltans",
                        "lieuDitComplementNom" : null,
                        "parcelles" : [ ],
                        "codeCommune" : "02131",
                        "nomCommune" : "Bucy-le-Long",
                        "certificationCommune" : true,
                        "position" : {
                                "type" : "Point",
                                "coordinates" : [
                                        3.398872,
                                        49.374724
                                ]
                        },
                        "positionType" : null,
 "**nomVoieAlt**" : {
                                "bre" : "nomVoieBreton",
                                "cos" : "nomVoieCorse"
                        },
                        "**lieuDitComplementNomAlt**" : {
                                "bre" : "LDCNbre",
                                "cos" : "LDCNCos"
                        }, 
                        "groupId" : "slug-00000-chemin-baltans"
                }
        ],
        "id" : "02131_68ihck_00001",
        "cleInterop" : "02131_68ihck_00001"

2022-07-20 11:53 UTC, mmortier commented
On passe maintenant par les codes de https://github.com/BaseAdresseNationale/shared-data

2022-07-20 12:38 UTC, mmortier commented
Modification de l'historique (renommage de commit et fusion de commit)

2022-07-20 12:39 UTC, jdesboeufs approved these changes

2022-07-20 12:39 UTC, jdesboeufs commented on lib/import/sources/bal.js
> +  const nomAlt = []
Il suffit en fait de faire :
```js
adresse.nomVoieAlt = item.nomVoieAlt ? JSON.parse(item.nomVoieAlt) : {}
adresse.lieuditComplementNomAlt = item.lieuditComplementNomAlt ? JSON.parse(item.lieuditComplementNomAlt) : {}
```

2022-07-20 12:39 UTC, jdesboeufs commented on package.json
> +    "@ban-team/shared-data": "^1.0.0",
Plus nécessaire du coup. Désolé :p

2022-07-20 12:40 UTC, jdesboeufs commented
Il manque la mise à jour de l'export au format BAL.
Addok peut attendre.

2022-07-20 13:06 UTC, mmortier commented on lib/compose/strategies/bal/voies.js
> +  const {nomVoieAlt} = adresses.find(a => a.nomVoie === nomVoie)
ok je fusionne

2022-07-20 13:40 UTC, jdesboeufs commented on lib/formatters/geojson.js
> +    lieuDitComplementNomAlt: numero.lieuDitComplementNomAlt,
oui

2022-07-20 13:41 UTC, jdesboeufs commented on package.json
> +    "@ban-team/shared-data": "^1.0.0",
En fait tu n'en as plus besoin car le `nomVoieAlt` et le `lieuditComplementNomAlt` arrivent déjà proprement au format JSON.

2022-07-20 13:42 UTC, jdesboeufs commented on package.json
> +    "@ban-team/shared-data": "^1.0.0",
D'ailleurs les fichiers `adresses-locales` avec langues régionales arrivent dans quelques minutes.

2022-07-21 09:33 UTC, mmortier commented
Retrait du commit relatif à l'export CSV de cette PR (utilisation du push force).
Prise en compte du format du nomVoieAlt et LDCNAlt des adresses-locales avec remove des données shared.

2022-07-21 09:50 UTC, jdesboeufs requested changes
C'est presque bon mais le `yarn.lock` est fortement modifié sans que ça ait un intérêt.

2022-07-21 10:27 UTC, jdesboeufs approved these changes

2022-07-21 10:27 UTC, merged