Initialiser les vues d adresses et de toponymes communs
BaseAdresseNationale/ban-plateforme pull request #436
Opened 2024-06-18 16:26 UTC by jbouhadoun

- créer vue adresses (avec toutes les données calculée par la query d'export de postgres => mongo)
- créer vue common_toponym (avec toutes les données calculée par la query d'export de postgres => mongo)
- Remplacer les queries par les vues.

issue #434

2024-06-19 16:38 UTC, antoineludeau approved these changes

2024-06-20 17:17 UTC, IGNFBourcier commented on lib/api/consumers/export-to-exploitation-db-consumer.js
> +
doublon avec L121-123, un seul est nécessaire. A voir si on accepte des districts "vide"

2024-06-21 10:59 UTC, antoineludeau requested changes

2024-06-21 10:59 UTC, antoineludeau commented on lib/api/consumers/export-to-exploitation-db-consumer.js
> +
Oui, il doit s'agir d'une erreur de rebase. Il faudrait retirer ces nouvelles lignes et laisser les lignes L121-123.

2024-06-24 09:19 UTC, merged