modification route lookup pour les lieux-dit ajout des numéros liés
BaseAdresseNationale/ban-plateforme pull request #83
Opened 2023-03-09 13:13 UTC by mmortier

Test lorsqu'on trouve un document dans le lookup des voies si c'est un lieu dit on ajoute les numéros liés (ie ceux qui ont llieux dit complement Nom rempli avec le libellé du lieux dit sur la commune).

Cela donne pour la Haute Folie à Breux sur Avre : (extrait)
**On récupère dans le numéro l'idVoie qui permettra ensuite de classer les numéros en les groupant par voie.
Il faudra donc faire une requête supplémentaire par idVoie pour récupérer le libellé à afficher dans la liste de l'explorateur adresse.data.gouv.fr.**
{
  "id": "27115_B023",
  "type": "lieu-dit",
  "idVoie": "27115_B023",
  "nomVoie": "La Haute Folie",
  "nomVoieAlt": {},
  "dateMAJ": "2020-07-03",
  "displayBBox": [
    1.0797,
    48.7713,
    1.0824,
    48.7731
  ],
  "commune": {
    "id": "27115",
    "nom": "Breux-sur-Avre",
    "code": "27115",
    "departement": {
      "nom": "Eure",
      "code": "27"
    },
    "region": {
      "nom": "Normandie",
      "code": "28"
    }
  },
  "numeros": [
    {
      "**idVoie": "27115_0043",**
      "numero": 2,
      "suffixe": null,
      "lieuDitComplementNomAlt": {},
      "parcelles": [],
      "sources": [
        "bal"
      ],
      "dateMAJ": "2021-09-06",
      "certifie": true,
      "position": {
        "type": "Point",
        "coordinates": [
          1.085651,
          48.773186
        ]
      },
      "positionType": "entrée",
      "sourcePosition": "bal",
      "codePostal": "27570",
      "libelleAcheminement": "BREUX SUR AVRE",
      "id": "27115_0043_00002"
    },
    
....

2023-03-09 13:56 UTC, IGNFBourcier commented on lib/models/commune.js
> +  const numeroLDFields = ['numero', 'suffixe', 'idVoie', 'lieuDitComplementNomAlt', 'parcelles', 'sources', 'position', 'positionType', 'sourcePosition', 'certifie', 'codePostal', 'libelleAcheminemen
```suggestion
  const numeroLDFields = ['numero', 'suffixe', 'idVoie', 'parcelles', 'sources', 'position', 'positionType', 'sourcePosition', 'certifie', 'codePostal', 'libelleAcheminement', 'id', 'dateMAJ']
```

2023-03-09 16:27 UTC, antoineludeau commented on lib/models/commune.js
> +      .find({lieuDitComplementNom: `${voie.nomVoie}`, codeCommune: `${voie.codeCommune}`})
Tu peux faire une jointure ici pour récupérer le nom des voies (https://www.w3schools.com/nodejs/nodejs_mongodb_join.asp)

2023-03-10 07:34 UTC, mmortier commented on lib/models/commune.js
> +      .find({lieuDitComplementNom: `${voie.nomVoie}`, codeCommune: `${voie.codeCommune}`})
Oui je crois qu'on peut tenter une jointure par contre je suis pas sure de la performance.

Tu as d'un côté site la récup des N id Voies -> Tu fais N requête sur les voies.
Vs tu fais une jointure sur chaque numéro pour avoir le nom de la voie... -> tu fais N * nb numéros jointures.

2023-03-10 10:32 UTC, mmortier commented on lib/models/commune.js
> +      .find({lieuDitComplementNom: `${voie.nomVoie}`, codeCommune: `${voie.codeCommune}`})
vu avec Antoine on reste comme ça

2023-03-10 10:41 UTC, antoineludeau requested changes

2023-03-10 10:41 UTC, antoineludeau commented on lib/models/commune.js
> +      .find({lieuDitComplementNom: `${voie.nomVoie}`, codeCommune: `${voie.codeCommune}`})
```suggestion
      .find({lieuDitComplementNom: voie.nomVoie, codeCommune: voie.codeCommune})
```

2023-03-10 10:52 UTC, antoineludeau approved these changes

2023-03-10 10:52 UTC, merged