Modification pour preparation Cog 2023
BaseAdresseNationale/ban-plateforme pull request #86
Opened 2023-03-10 08:17 UTC by vinsag

Des modifications ont été effectuées dans différents fichiers en préparation de la mise en place du COG 2023.
Il faudra penser à regenerer le yarn.lock quand la version du fantoir sera en release.

Fix #84

2023-03-10 12:46 UTC, mmortier requested changes

2023-03-10 12:46 UTC, mmortier commented on package.json
> +    "@etalab/fantoir": "^0.15.0",
Je crois que tu dois relancer yarn pour mettre à jour le .lock et il faudra changer la version du validateur aussi quand elle sera à jour avec le COG 2023

2023-03-15 16:01 UTC, nkokla approved these changes
Je n'ai pas lancé de test. (Comment on peux tester ? 😝)
Sinon, ça semble OK coté code.

2023-03-15 16:01 UTC, nkokla commented on lib/util/contours.js
> +  const communesFile = await got('https://adresse.data.gouv.fr/data/contours-administratifs/2023/geojson/communes-50m.geojson').json()
On devrait peut-être fixer une variable d'env du type `MILLESIME=2023`qui pourrait ensuite etre utilisé pour le `COG`, `Gazetteer` et `Fantoir`.
Tu en penses quoi ?

2023-03-16 13:43 UTC, vinsag commented on lib/util/contours.js
> +  const communesFile = await got('https://adresse.data.gouv.fr/data/contours-administratifs/2023/geojson/communes-50m.geojson').json()
On le fera quand on reprendra le code

2023-03-22 14:36 UTC, closed without merging